### ISSUE TITLE
Error: Invalid executable format.

### ISSUE THREAD

**Issue by lepotekil** [millers-crossing/sim-ba#1]
I have this error
![image](https://user-images.githubusercontent.com/52042546/111952218-163a5e80-8ae5-11eb-9e70-186097548efd.png)

Do you know how i can compile Source.cpp on linux ?

**Comment by OccamsXor** [comment]
Can you check if you can download the remote malware.exe using wireshark or something else? The error you get is from Source.cpp:111 and that line checks if the file downloaded from url has legitimate DOS Header. 

I don't know a direct way to compile it on linux. But, I would try changing some types and using mingw.

**Comment by lepotekil** [comment]
This morning I tested the project and it works. I don't know where the problem came from. This is a really good application 👍 

Yes, please, can you make it compilable with mingw?
Like ==> x86_64-w64-mingw32-g++ sim-ba.cpp

**Comment by OccamsXor** [comment]
I don't plan to work on MinGW compilable version right now but PRs are always appreciated :D

**Comment by lepotekil** [comment]
Can you explain me what is "PRs" ? :)

**Comment by OccamsXor** [comment]
Pull Requests are always welcomed!

**Comment by lepotekil** [comment]
Ok thank you ;)
